name: Publish Native iOS Libraries

on:
  workflow_dispatch:
    inputs:
      plugins:
        description: 'Specify a set of plugins to publish (as a JSON array, ex: [\"camera\", \"browser\"])'
        required: true
jobs:
  publish-ios:
    runs-on: macos-15
    if: github.event.inputs.plugins != '[]'
    timeout-minutes: 30
    strategy:
      matrix:
        plugin: ${{ fromJson(github.event.inputs.plugins) }}
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_16.app
      - run: xcrun simctl list > /dev/null
      - run: xcodebuild -downloadPlatform iOS
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: actions/checkout@v5
      - name: Install Cocoapods
        run: | 
          gem install cocoapods
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          npm run publish:cocoapod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        working-directory: ${{ matrix.plugin }}
